version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: type-coverage
    versions:
    - 2.14.9
    - 2.15.0
    - 2.15.1
    - 2.16.0
    - 2.16.1
    - 2.16.2
    - 2.16.3
    - 2.17.0
    - 2.17.2
    - 2.17.3
  - dependency-name: typescript
    versions:
    - 3.9.7
    - 3.9.8
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: jquery
    versions:
    - 3.5.1
